### PR TITLE
Tools

### PR DESCRIPTION
**Pull request by isaacholt100**

### CODE REVIEW

**Comment by Joseph-Rance** [comment]
@KashParty probs should have said this before I accepted, but i think there may be a problem

**Comment by Joseph-Rance** [comment]
This might be stupid, but should agenda have stuff in it by default? I feel like he added this in debugging

**Comment by Joseph-Rance** [comment]
added to agenda.json:
```
[
  {
    "subject": "Maths",
    "desc": "Do surds hw",
    "date": "Fri Jan 10 2020 13:27:07 GMT+0000 (Greenwich Mean Time)",
    "time": false
  },
  {
    "subject": "English",
    "desc": "Retest",
    "date": "Thu Jan 04 2020 13:27:07 GMT+0000 (Greenwich Mean Time)",
    "time": "All Day"
  },
  {
    "subject": "Physics",
    "desc": "Prove one-electron-universe",
    "date": "Wed Jan 08 2020 13:27:07 GMT+0000 (Greenwich Mean Time)",
    "time": "All Day"
  },
  {
    "subject": "Biology",
    "desc": "Revise for test",
    "date": "Thu Jan 02 2020 13:27:07 GMT+0000 (Greenwich Mean Time)",
    "time": false
  },
  {
    "subject": "Geography",
    "desc": "Coasts hw",
    "date": "Thu Jan 02 2020 13:27:07 GMT+0000 (Greenwich Mean Time)",
    "time": false
  },
  {
    "subject": "Maths",
    "desc": "Read chapter on graph of a^x and log a (x)",
    "date": "Sat Jan 04 2020 13:27:07 GMT+0000 (Greenwich Mean Time)",
    "time": "All Day"
  }
]
```

**Comment by Joseph-Rance** [comment]
I'll let @maximiseuk review this because I'm not sure about it

**Comment by maximiseuk** [comment]
I think it's pretty obvious that that's just for debugging and probably needs to be removed. I'm not sure if the user will ever see that though because it's probably replaced with the agenda fetched from the database.

**Comment by Joseph-Rance** [comment]
ok i wasn't sure as I have had little involvement with the js. I'll change them for him

**Comment by Joseph-Rance** [comment]
@maximiseuk I think i've fixed the issue but I'm not 100% sure so I'll leave this one for u to review

**Comment by Joseph-Rance** [comment]
Also, it has a similar thing in master so it obvs. doesn't really matter but I do think it is better this way regardless as commits to master should not really have debugging stuff in them

**Pull request merged**
